version: '3'

tasks:
  default:
    desc: "The default task" 
    cmds:
      - clear
      # - go run ./cmd/mdtran
      # - go test -run ^TestMockAll$ github.com/117503445/markdown-translate/test -v -count=1
      - go test -run ^TestCfg$ github.com/117503445/markdown-translate/test -v -count=1