name: Github Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - run: docker build -t builder -f Dockerfile.builder .

      - run: docker run --rm -v $(pwd):/workspace builder

      # https://github.com/softprops/action-gh-release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            mdtran-darwin-amd64
            mdtran-darwin-arm64
            mdtran-linux-amd64
            mdtran-linux-arm64
            mdtran-windows-amd64.exe
            mdtran-windows-arm64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}